### ISSUE TITLE
How to query a substructure in turtle file?

### ISSUE THREAD

**Issue by xiaoxiaoAurora** [RDFLib/rdflib#1039]
**Hello!
I want to find the following structure with SPARQL :**

```
PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#>
SELECT ?sent_id ?dependency ?head ?edge
WHERE {
BIND("时候" as ?head)
?depid conll:WORD ?dependency ;
	conll:HEAD ?headid ;
	conll:EDGE ?edge .
?headid conll:WORD ?head .
}
```

**1. When running the following code:**

```
    graph = rdflib.Graph()
    graph.parse(r"../database/rdf-data/test.ttl", format="turtle")
    pattern = """@prefix conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#> .
                    SELECT ?sent_id ?dependency ?head ?edge WHERE {
                    BIND('时候' as ?head)
                    ?depid conll:WORD ?dependency ;
                    conll:HEAD ?headid ;
                    conll:EDGE ?edge .
                    ?headid conll:WORD ?head .
                }"""
    result_query = graph.query(pattern)
    for row in result_query:
        print(row)
```

**2. There are the following problems:** 
```
Traceback (most recent call last):
  File "F:/workspace/Chinese-CFL-UD-RetrievalWeb/src/dependencytree_query.py", line 66, in <module>
    Query_DependencyTree('')
  File "F:/workspace/Chinese-CFL-UD-RetrievalWeb/src/dependencytree_query.py", line 56, in Query_DependencyTree
    result_query = graph.query(pattern)
  File "E:\Anaconda3\lib\site-packages\rdflib\graph.py", line 1089, in query
    query_object, initBindings, initNs, **kwargs))
  File "E:\Anaconda3\lib\site-packages\rdflib\plugins\sparql\processor.py", line 74, in query
    parsetree = parseQuery(strOrQuery)
  File "E:\Anaconda3\lib\site-packages\rdflib\plugins\sparql\parser.py", line 1058, in parseQuery
    return Query.parseString(q, parseAll=True)
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 1632, in parseString
    raise exc
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 3545, in parseImpl
    raise maxException
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "E:\Anaconda3\lib\site-packages\pyparsing.py", line 2521, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected {SelectQuery | ConstructQuery | DescribeQuery | AskQuery} (at char 0), (line:1, col:1)
```

**3. The data of test.ttl  is shown below:**

```
@prefix : <https://github.com/UniversalDependencies/UD_Chinese#> .
@prefix powla: <http://purl.org/powla/powla.owl#> .
@prefix conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix terms: <http://purl.org/acoli/open-ie/> .
@prefix x: <http://purl.org/acoli/conll-rdf/xml#> .
@prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
:s1_0 a nif:Sentence; rdfs:comment " sent_id = CFL_A_1-1a_ori\\n text = 2012年12月我在韩国留学的时候，有一天接到一个通知。" .
:s1_1 a nif:Word; conll:WORD "2012年"; conll:EDGE "obl:tmod"; conll:HEAD :s1_6; conll:ID "1"; conll:LEMMA "2012年"; conll:MISC "SpaceAfter=No"; conll:UPOS "NOUN"; nif:nextWord :s1_2 .
:s1_2 a nif:Word; conll:WORD "12月"; conll:EDGE "flat"; conll:HEAD :s1_1; conll:ID "2"; conll:LEMMA "12月"; conll:MISC "SpaceAfter=No"; conll:UPOS "NOUN"; nif:nextWord :s1_3 .
:s1_3 a nif:Word; conll:WORD "我"; conll:EDGE "nsubj"; conll:HEAD :s1_6; conll:ID "3"; conll:LEMMA "我"; conll:MISC "SpaceAfter=No"; conll:UPOS "PRON"; nif:nextWord :s1_4 .
:s1_4 a nif:Word; conll:WORD "在"; conll:EDGE "case"; conll:HEAD :s1_5; conll:ID "4"; conll:LEMMA "在"; conll:MISC "SpaceAfter=No"; conll:UPOS "ADP"; nif:nextWord :s1_5 .
:s1_5 a nif:Word; conll:WORD "韩国"; conll:EDGE "obl"; conll:HEAD :s1_6; conll:ID "5"; conll:LEMMA "韩国"; conll:MISC "SpaceAfter=No"; conll:UPOS "PROPN"; nif:nextWord :s1_6 .
:s1_6 a nif:Word; conll:WORD "留学"; conll:EDGE "acl"; conll:HEAD :s1_8; conll:ID "6"; conll:LEMMA "留学"; conll:MISC "SpaceAfter=No"; conll:UPOS "VERB"; nif:nextWord :s1_7 .
:s1_7 a nif:Word; conll:WORD "的"; conll:EDGE "mark:rel"; conll:HEAD :s1_6; conll:ID "7"; conll:LEMMA "的"; conll:MISC "SpaceAfter=No"; conll:UPOS "PART"; nif:nextWord :s1_8 .
:s1_8 a nif:Word; conll:WORD "时候"; conll:EDGE "obl:tmod"; conll:HEAD :s1_13; conll:ID "8"; conll:LEMMA "时候"; conll:MISC "SpaceAfter=No"; conll:UPOS "NOUN"; nif:nextWord :s1_9 .
:s1_9 a nif:Word; conll:WORD "，"; conll:EDGE "punct"; conll:HEAD :s1_8; conll:ID "9"; conll:LEMMA "，"; conll:MISC "SpaceAfter=No"; conll:UPOS "PUNCT"; nif:nextWord :s1_10 .
:s1_10 a nif:Word; conll:WORD "有"; conll:EDGE "advcl"; conll:HEAD :s1_13; conll:ID "10"; conll:LEMMA "有"; conll:MISC "SpaceAfter=No"; conll:UPOS "VERB"; nif:nextWord :s1_11 .
:s1_11 a nif:Word; conll:WORD "一"; conll:EDGE "nummod"; conll:HEAD :s1_12; conll:ID "11"; conll:LEMMA "一"; conll:MISC "SpaceAfter=No"; conll:UPOS "NUM"; nif:nextWord :s1_12 .
:s1_12 a nif:Word; conll:WORD "天"; conll:EDGE "obj"; conll:HEAD :s1_10; conll:ID "12"; conll:LEMMA "天"; conll:MISC "SpaceAfter=No"; conll:UPOS "NOUN"; nif:nextWord :s1_13 .
:s1_13 a nif:Word; conll:WORD "接"; conll:EDGE "root"; conll:HEAD :s1_0; conll:ID "13"; conll:LEMMA "接"; conll:MISC "SpaceAfter=No"; conll:UPOS "VERB"; nif:nextWord :s1_14 .
:s1_14 a nif:Word; conll:WORD "到"; conll:EDGE "compound:vv"; conll:HEAD :s1_13; conll:ID "14"; conll:LEMMA "到"; conll:MISC "SpaceAfter=No"; conll:UPOS "VERB"; nif:nextWord :s1_15 .
:s1_15 a nif:Word; conll:WORD "一"; conll:EDGE "nummod"; conll:HEAD :s1_17; conll:ID "15"; conll:LEMMA "一"; conll:MISC "SpaceAfter=No"; conll:UPOS "NUM"; nif:nextWord :s1_16 .
:s1_16 a nif:Word; conll:WORD "个"; conll:EDGE "clf"; conll:HEAD :s1_15; conll:ID "16"; conll:LEMMA "个"; conll:MISC "SpaceAfter=No"; conll:UPOS "NOUN"; nif:nextWord :s1_17 .
:s1_17 a nif:Word; conll:WORD "通知"; conll:EDGE "obj"; conll:HEAD :s1_13; conll:ID "17"; conll:LEMMA "通知"; conll:MISC "SpaceAfter=No"; conll:UPOS "NOUN"; nif:nextWord :s1_18 .
:s1_18 a nif:Word; conll:WORD "。"; conll:EDGE "punct"; conll:HEAD :s1_13; conll:ID "18"; conll:LEMMA "。"; conll:MISC "SpaceAfter=No"; conll:UPOS "PUNCT" .
```

**Comment by dwinston** [comment]
Your SPARQL string isn't well-formed in your code example, but it's fine in your first block. In the code example you use the turtle syntax for prefixes, but that's not what SPARQL uses. Use `PREFIX conll: <http://ufal.mff.cuni.cz/conll2009-st/task-description.html#>` before `SELECT` in the string like you do in the first block.

Also, in future, please post to [stackoverflow with the rdflib tag](https://stackoverflow.com/questions/tagged/rdflib) with questions that aren't necessarily issues with rdflib.

**Comment by nicholascar** [comment]
I'm closing this as indeed, this kind of "how to" questions should be on stackoverflow.
