### ISSUE TITLE
Parser errors on permanent redirect

### ISSUE THREAD

**Issue by jimmccusker** [RDFLib/rdflib#1040]
This is a problem when loading DC Terms, which is a core vocabulary. Permanent redirects should result in a load, not error.

``` python
import rdflib
g = rdflib.Graph()
g.parse(location='http://purl.org/dc/terms/',format='turtle')
```

yields:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python3.5/site-packages/rdflib/graph.py", line 1023, in parse
    data=data, format=format)
  File "/venv/lib/python3.5/site-packages/rdflib/parser.py", line 191, in create_input_source
    input_source = URLInputSource(absolute_location, format)
  File "/venv/lib/python3.5/site-packages/rdflib/parser.py", line 111, in __init__
    file = urlopen(req)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect
```

**Comment by tgbugs** [comment]
Confirmed here as well.

**Comment by aucampia** [comment]
The problem here is that urllib does not handle 308, but it does handle 302 and 303. Working on adding handling outside of the library.

**Comment by aucampia** [comment]
See also this: https://bugs.python.org/issue40321
