### ISSUE TITLE
csv2rdf uses Python 2 features broken by Python 3

### ISSUE THREAD

**Issue by davidianjoy** [RDFLib/rdflib#1116]
I have tried to run **csv2rdf** under both Windows 10 and a(n Alpine) Linux Docker container and it failed both times, due to differences between Python 2 and Python 3 strings and bytestreams.

I have been able to patch the module using the following three **sed** commands:

```sh
# Replace .next() with next(...)
sed -i 's/header_labels = list(csvreader.next())/header_labels = list(next(csvreader))/g' /usr/local/lib/python3.8/site-packages/rdflib/tools/csv2rdf.py

# Python 3 strings are natively Unicode
sed -i 's/yield \[str(cell, "utf-8", errors="replace") for cell in row\]/yield \[cell for cell in row\]/g' /usr/local/lib/python3.8/site-packages/rdflib/tools/csv2rdf.py

# Reference https://stackoverflow.com/questions/4374455/how-to-set-sys-stdout-encoding-in-python-3
sed -i 's/self.OUT = codecs.getwriter("utf-8")(sys.stdout, errors="replace")/self.OUT = codecs.getwriter("utf-8")(sys.stdout.detach(), errors="replace")/g' /usr/local/lib/python3.8/site-packages/rdflib/tools/csv2rdf.py
```

but this seems to alter some of **csv2rdf**'s incidental behaviour, such as showing the help text and printing extra output about the buffer being detatched.

It would be good if someone who knew what they were doing could take a look at this and update this tool for Python 3.

**Comment by davidianjoy** [comment]
No problem. I was using a sample CSV file from AWS: [Sacramentorealestatetransactions.csv](http://samplecsvs.s3.amazonaws.com/Sacramentorealestatetransactions.csv).

The log messages produced from running (the unpatched) `csv2rdf` against this CSV file were:

> Output to \<stdout\>
/usr/local/lib/python3.8/site-packages/rdflib/tools/csv2rdf.py:337: UserWarning: No base given, using http://example.org/instances/
  warnings.warn("No base given, using http://example.org/instances/")
/usr/local/lib/python3.8/site-packages/rdflib/tools/csv2rdf.py:341: UserWarning: No property base given, using http://example.org/property/
  warnings.warn("No property base given, using http://example.org/property/")
Traceback (most recent call last):
  File "/usr/local/bin/csv2rdf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/rdflib/tools/csv2rdf.py", line 552, in main
    csv2rdf.convert(csv_reader(fileinput.input(files), delimiter=csv2rdf.DELIM))
  File "/usr/local/lib/python3.8/site-packages/rdflib/tools/csv2rdf.py", line 349, in convert
    header_labels = list(csvreader.next())
AttributeError: 'generator' object has no attribute 'next'

The first **sed** call patches this by replacing `csvreader.next()` with `next(csvreader)` - this then leads to further error messages, and so forth.

**Comment by davidianjoy** [comment]
I've just spotted other Python 2 -> Python 3 issues like line 135:

`r = rdflib.URIRef(prefix + quote(x.encode("utf8").replace(" ", "_"), safe=""))`

and line 381:

`quote(x.encode("utf8").replace(" ", "_"), safe="")`

I _think_ that all you need to get is get rid of the `.encode()` function calls - but this is starting to look as if the whole tool should be overhauled
