### ISSUE TITLE
SPARQL engine breaks on impor on Python 3.7.3

### ISSUE THREAD

**Issue by andrecastro0o** [RDFLib/rdflib#1204]
(Related to https://github.com/RDFLib/rdflib/issues/1190  but concerning Python 3.7.3

Any one experienced `rdflib.plugins.sparql` breaking on Python 3.7.3 

```
python -c 'import rdflib.plugins.sparql'
RDFLib Version: 5.0.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vagrant/ontology2smw/venv/lib/python3.7/site-packages/rdflib/plugins/sparql/__init__.py", line 33, in <module>
    from . import parser
  File "/home/vagrant/ontology2smw/venv/lib/python3.7/site-packages/rdflib/plugins/sparql/parser.py", line 184, in <module>
    Param('prefix', PN_PREFIX)) + Suppress(':').leaveWhitespace()
  File "/home/vagrant/ontology2smw/venv/lib/python3.7/site-packages/rdflib/plugins/sparql/parserutils.py", line 114, in __init__
    self.name = name
AttributeError: can't set attribute
```

I have build an Cli application using RDFlib lib, mainly for performing SPARQL queries.
all has been fine on my development machine where I am running Python 3.7.3 (in a venv),

But because I received https://github.com/TIBHannover/ontology2smw/issues/33 I tried to build the application in a Debian VM with   Python 3.7.3 and this erro has appeared.

Any ideas if this can or be fixed soon?

Thank you so much

**Comment by andrecastro0o** [comment]
OK, think I need to specify the version of pyparsing to 2.4.7

```
pip install pyparsing==2.4.7
Collecting pyparsing==2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: pyparsing
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.0.0b1
    Uninstalling pyparsing-3.0.0b1:
      Successfully uninstalled pyparsing-3.0.0b1
Successfully installed pyparsing-2.4.7
``` 

`python -c 'import rdflib.plugins.sparql'` 
* Response: `RDFLib Version: 5.0.0`
