### ISSUE TITLE
Simple SPARQL queries not working on python 3.9.1 / RDFlib 5.0.0

### ISSUE THREAD

**Issue by wood-chris** [RDFLib/rdflib#1215]
At first I didn't have `requests` installed in the environment (I couldn't see this explicitly mentioned in the docs, should it be added?):

```python

>>> g.parse("test.nt", format="nt")
<Graph identifier=Nac4df00ff5cc411c9e88a3ea1f2e82db (<class 'rdflib.graph.Graph'>)>
>>> g.query("SELECT * FROM {?a ?b ?c . }")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chris/opt/miniconda3/envs/testrdf/lib/python3.9/site-packages/rdflib/graph.py", line 1127, in query
    result = plugin.get(result, query.Result)
  File "/Users/chris/opt/miniconda3/envs/testrdf/lib/python3.9/site-packages/rdflib/plugin.py", line 107, in get
    return p.getClass()
  File "/Users/chris/opt/miniconda3/envs/testrdf/lib/python3.9/site-packages/rdflib/plugin.py", line 69, in getClass
    module = __import__(self.module_path, globals(), locals(), [""])
  File "/Users/chris/opt/miniconda3/envs/testrdf/lib/python3.9/site-packages/rdflib/plugins/sparql/__init__.py", line 37, in <module>
    from .processor import prepareQuery, processUpdate
  File "/Users/chris/opt/miniconda3/envs/testrdf/lib/python3.9/site-packages/rdflib/plugins/sparql/processor.py", line 18, in <module>
    from rdflib.plugins.sparql.evaluate import evalQuery
  File "/Users/chris/opt/miniconda3/envs/testrdf/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 20, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
after installing it, simple SPARQL queries don't work after loading an NT file:

```python
>>> res = g.query("SELECT * FROM {?a ?b ?c . } limit 10")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chris/opt/miniconda3/envs/testrdf/lib/python3.9/site-packages/rdflib/graph.py", line 1131, in query
    return result(processor.query(query_object, initBindings, initNs, **kwargs))
  File "/Users/chris/opt/miniconda3/envs/testrdf/lib/python3.9/site-packages/rdflib/plugins/sparql/processor.py", line 76, in query
    parsetree = parseQuery(strOrQuery)
  File "/Users/chris/opt/miniconda3/envs/testrdf/lib/python3.9/site-packages/rdflib/plugins/sparql/parser.py", line 1060, in parseQuery
    return Query.parseString(q, parseAll=True)
  File "/Users/chris/opt/miniconda3/envs/testrdf/lib/python3.9/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/Users/chris/opt/miniconda3/envs/testrdf/lib/python3.9/site-packages/pyparsing.py", line 2899, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected {SelectQuery | ConstructQuery | DescribeQuery | AskQuery}, found 'F'  (at char 9), (line:1, col:10)
```

**Comment by nicholascar** [comment]
Hi @wood-chris, yes that requirement for `requests` is a pain, but it's been removed recently #1175, so if you load RDFlib from HEAD and, in future, use 6.0.0, you won't have that problem.

Regarding your second problem: that's not a valid SPARQL query, as RDFlib is telling you! Swap `FROM` to `WHERE`

```
SELECT * WHERE { ?a ?b ?c .} LIMIT 10
```
`FROM` in SPARQL is used to indicate a data source to query - like specifying a table in SQL - but you've used it where you should be setting a pattern, the very restrictive `?a ?b ?c`. 

So I'm going to close this as there's really no issue here that's not either addressed of user error! Cheers.

**Comment by wood-chris** [comment]
errr, good point about the invalid query! sorry! I've been looking at too much SQL lately and had syntax blindness 😅
