### ISSUE TITLE
5.0.0: test suit is failing

### ISSUE THREAD

**Issue by kloczek** [RDFLib/rdflib#1229]
```
======================================================================
FAIL: test.test_sparql_service.test_service
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_sparql_service.py", line 20, in test_service
    assert len(results) == 2
AssertionError:
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): dbpedia.org:80
urllib3.connectionpool: DEBUG: http://dbpedia.org:80 "GET /sparql?query=+select+%3FdbpHypernym+%3FdbpComment%0A++++where%0A++++%7B%0A++++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FJohn_Lilburne%3E%0A++++++++%3Chttp%3A%2F%2Fpurl.org%2Flinguistics%2Fgold%2Fhypernym%3E+%3FdbpHypernym+%3B%0A++++++++%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23comment%3E+%3FdbpComment+.%0A%0A++++%7D+&output=json HTTP/1.1" 200 136
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test.test_sparql_service.test_service_with_bind
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_sparql_service.py", line 42, in test_service_with_bind
    assert len(results) == 2
AssertionError:
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): dbpedia.org:80
urllib3.connectionpool: DEBUG: http://dbpedia.org:80 "GET /sparql?query=+select+%3FdbpHypernym+%3FdbpComment+%3FdbpDeathPlace%0A++++where%0A++++%7B%0A++++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FJohn_Lilburne%3E%0A++++++++%3Chttp%3A%2F%2Fpurl.org%2Flinguistics%2Fgold%2Fhypernym%3E+%3FdbpHypernym+%3B%0A++++++++%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23comment%3E+%3FdbpComment+%3B%0A++++++++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FdeathPlace%3E+%3FdbpDeathPlace+.%0A%0A++++%7D+VALUES+%28%3FdbpDeathPlace%29+%7B%28%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FEltham%3E%29%7D&output=json HTTP/1.1" 200 153
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test.test_sparql_service.test_service_with_values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_sparql_service.py", line 64, in test_service_with_values
    assert len(results) == 2
AssertionError:
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): dbpedia.org:80
urllib3.connectionpool: DEBUG: http://dbpedia.org:80 "GET /sparql?query=+select+%3FdbpHypernym+%3FdbpComment+%3FdbpDeathPlace%0A++++where%0A++++%7B%0A++++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FJohn_Lilburne%3E%0A++++++++%3Chttp%3A%2F%2Fpurl.org%2Flinguistics%2Fgold%2Fhypernym%3E+%3FdbpHypernym+%3B%0A++++++++%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23comment%3E+%3FdbpComment+%3B%0A++++++++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FdeathPlace%3E+%3FdbpDeathPlace+.%0A%0A++++%7D+VALUES+%28%3FdbpHypernym+%3FdbpDeathPlace%29+%7B%28%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLeveller%3E+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLondon%3E%29%7D&output=json HTTP/1.1" 200 153
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): dbpedia.org:80
urllib3.connectionpool: DEBUG: http://dbpedia.org:80 "GET /sparql?query=+select+%3FdbpHypernym+%3FdbpComment+%3FdbpDeathPlace%0A++++where%0A++++%7B%0A++++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FJohn_Lilburne%3E%0A++++++++%3Chttp%3A%2F%2Fpurl.org%2Flinguistics%2Fgold%2Fhypernym%3E+%3FdbpHypernym+%3B%0A++++++++%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23comment%3E+%3FdbpComment+%3B%0A++++++++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FdeathPlace%3E+%3FdbpDeathPlace+.%0A%0A++++%7D+VALUES+%28%3FdbpHypernym+%3FdbpDeathPlace%29+%7B%28%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLeveller%3E+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FEltham%3E%29%7D&output=json HTTP/1.1" 200 153
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 3231 tests in 28.250s

FAILED (failures=3, skipped=91)
Test failed: <unittest.runner.TextTestResult run=3231 errors=0 failures=3>
error: Test failed: <unittest.runner.TextTestResult run=3231 errors=0 failures=3>
```

**Comment by white-gecko** [comment]
I can reproduce this behavior on my system. This raises the question, why don't we have this issue on travis: https://travis-ci.org/github/RDFLib/rdflib/jobs/752949814 ?

**Comment by white-gecko** [comment]
We clearly have some problem here. It also happens for current CI-tests.

**Comment by kloczek** [comment]
Any plans to make new release?
Looks like there are now more than 250 commits since last release ..

**Comment by ashleysommer** [comment]
@kloczek 
Yes, our release roadmap is planned. We are working toward a big 6.0.0 release. This is going to be even bigger than the 5.0.0 release, and includes some big changes, so its important to get everything right.

**Comment by kloczek** [comment]
FYI pytest otput:
```console
+ /usr/bin/python3 -Bm pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, httpbin-1.0.0, xdist-2.2.1, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, pyfakefs-4.4.0, freezegun-0.4.2, cases-3.4.6, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, flaky-3.7.0, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, hypothesis-6.13.7, Faker-8.4.0, cov-2.12.1
collected 427 items / 3 skipped / 424 selected

. .                                                                                                                                                                  [  0%]
test/test_aggregate_graphs.py .                                                                                                                                      [  0%]
test/test_auditable.py ........................                                                                                                                      [  6%]
test/test_canonicalization.py ...                                                                                                                                    [  6%]
test/test_comparison.py ..........                                                                                                                                   [  9%]
test/test_conjunctive_graph.py ..x                                                                                                                                   [  9%]
test/test_conneg.py .                                                                                                                                                [ 10%]
test/test_conventions.py .                                                                                                                                           [ 10%]
test/test_core_sparqlstore.py .                                                                                                                                      [ 10%]
test/test_dataset.py sss...                                                                                                                                          [ 11%]
test/test_datetime.py .......                                                                                                                                        [ 13%]
test/test_dawg.py x                                                                                                                                                  [ 13%]
test/test_diff.py ..                                                                                                                                                 [ 14%]
test/test_duration.py ......                                                                                                                                         [ 15%]
test/test_empty_xml_base.py ..                                                                                                                                       [ 16%]
test/test_evaluate_bind.py x                                                                                                                                         [ 16%]
test/test_events.py .                                                                                                                                                [ 16%]
test/test_expressions.py ......                                                                                                                                      [ 18%]
test/test_extras_external_graph_libs.py ss                                                                                                                           [ 18%]
test/test_finalnewline.py .                                                                                                                                          [ 18%]
test/test_graph.py sssssss.......                                                                                                                                    [ 22%]
test/test_graph_context.py ssssssssss..........                                                                                                                      [ 26%]
test/test_graph_formula.py x                                                                                                                                         [ 26%]
test/test_graph_items.py .                                                                                                                                           [ 27%]
test/test_hex_binary.py ..                                                                                                                                           [ 27%]
test/test_initbindings.py ..........................                                                                                                                 [ 33%]
test/test_iomemory.py ..                                                                                                                                             [ 34%]
test/test_issue084.py ........                                                                                                                                       [ 36%]
test/test_issue160.py .                                                                                                                                              [ 36%]
test/test_issue161.py .                                                                                                                                              [ 36%]
test/test_issue184.py .                                                                                                                                              [ 36%]
test/test_issue209.py .                                                                                                                                              [ 37%]
test/test_issue223.py .                                                                                                                                              [ 37%]
test/test_issue247.py ..                                                                                                                                             [ 37%]
test/test_issue248.py .                                                                                                                                              [ 38%]
test/test_issue274.py ................................                                                                                                               [ 45%]
test/test_issue363.py ..                                                                                                                                             [ 46%]
test/test_issue379.py ..                                                                                                                                             [ 46%]
test/test_issue381.py .......                                                                                                                                        [ 48%]
test/test_issue432.py .                                                                                                                                              [ 48%]
test/test_issue446.py .                                                                                                                                              [ 48%]
test/test_issue492.py .                                                                                                                                              [ 48%]
test/test_issue523.py .                                                                                                                                              [ 49%]
test/test_issue532.py .                                                                                                                                              [ 49%]
test/test_issue535.py .                                                                                                                                              [ 49%]
test/test_issue545.py .                                                                                                                                              [ 49%]
test/test_issue554.py .                                                                                                                                              [ 50%]
test/test_issue563.py ..                                                                                                                                             [ 50%]
test/test_issue579.py .                                                                                                                                              [ 50%]
test/test_issue604.py .                                                                                                                                              [ 50%]
test/test_issue655.py .                                                                                                                                              [ 51%]
test/test_issue715.py .                                                                                                                                              [ 51%]
test/test_issue733.py ..                                                                                                                                             [ 51%]
test/test_issue920.py .                                                                                                                                              [ 52%]
test/test_issue923.py .                                                                                                                                              [ 52%]
test/test_issue953.py .                                                                                                                                              [ 52%]
test/test_issue_git_200.py .                                                                                                                                         [ 52%]
test/test_issue_git_336.py .                                                                                                                                         [ 53%]
test/test_literal.py .................                                                                                                                               [ 57%]
test/test_memory_store.py .                                                                                                                                          [ 57%]
test/test_mulpath_n3.py .                                                                                                                                            [ 57%]
test/test_n3.py ................                                                                                                                                     [ 61%]
test/test_n3_suite.py x                                                                                                                                              [ 61%]
test/test_namespace.py ......                                                                                                                                        [ 62%]
test/test_nodepickler.py ...                                                                                                                                         [ 63%]
test/test_nquads.py .....                                                                                                                                            [ 64%]
test/test_nquads_w3c.py x                                                                                                                                            [ 65%]
test/test_nt_misc.py ...............                                                                                                                                 [ 68%]
test/test_nt_w3c.py x                                                                                                                                                [ 68%]
test/test_parser.py .                                                                                                                                                [ 69%]
test/test_parser_helpers.py .                                                                                                                                        [ 69%]
test/test_path_div_future.py .                                                                                                                                       [ 69%]
test/test_prefixTypes.py .                                                                                                                                           [ 69%]
test/test_preflabel.py .....                                                                                                                                         [ 70%]
test/test_prettyxml.py .......                                                                                                                                       [ 72%]
test/test_rdf_lists.py ..                                                                                                                                            [ 73%]
test/test_rdfxml.py ..                                                                                                                                               [ 73%]
test/test_roundtrip.py xx                                                                                                                                            [ 73%]
test/test_seq.py ..                                                                                                                                                  [ 74%]
test/test_serializexml.py .....                                                                                                                                      [ 75%]
test/test_slice.py .                                                                                                                                                 [ 75%]
test/test_sparql.py ......                                                                                                                                           [ 77%]
test/test_sparql_agg_distinct.py ....                                                                                                                                [ 78%]
test/test_sparql_agg_undef.py x.                                                                                                                                     [ 78%]
test/test_sparql_construct_bindings.py .                                                                                                                             [ 78%]
test/test_sparql_service.py FFF...                                                                                                                                   [ 80%]
test/test_sparqlstore.py ....                                                                                                                                        [ 81%]
test/test_swap_n3.py x                                                                                                                                               [ 81%]
test/test_term.py .......                                                                                                                                            [ 83%]
test/test_trig.py .........s.                                                                                                                                        [ 85%]
test/test_trig_w3c.py x                                                                                                                                              [ 85%]
test/test_trix_parse.py ...                                                                                                                                          [ 86%]
test/test_trix_serialize.py ..                                                                                                                                       [ 87%]
test/test_tsvresults.py .                                                                                                                                            [ 87%]
test/test_turtle_serialize.py .....                                                                                                                                  [ 88%]
test/test_turtle_sort_issue613.py ..                                                                                                                                 [ 88%]
test/test_turtle_w3c.py x                                                                                                                                            [ 89%]
test/test_util.py .........................................                                                                                                          [ 98%]
test/test_wide_python.py .                                                                                                                                           [ 99%]
test/test_xmlliterals.py ....                                                                                                                                        [100%]

================================================================================= FAILURES =================================================================================
_______________________________________________________________________________ test_service _______________________________________________________________________________

    def test_service():
        g = Graph()
        q = '''select ?dbpHypernym ?dbpComment
        where
        { service <http://DBpedia.org/sparql>
        { select ?dbpHypernym ?dbpComment
        where
        {
        <http://dbpedia.org/resource/John_Lilburne>
            <http://purl.org/linguistics/gold/hypernym> ?dbpHypernym ;
            <http://www.w3.org/2000/01/rdf-schema#comment> ?dbpComment .

        } }  } limit 2'''
        results = g.query(q)
>       assert len(results) == 2
E       assert 0 == 2
E        +  where 0 = len(<rdflib.plugins.sparql.processor.SPARQLResult object at 0x7f814bede310>)

test/test_sparql_service.py:20: AssertionError
__________________________________________________________________________ test_service_with_bind __________________________________________________________________________

    def test_service_with_bind():
        g = Graph()
        q = '''select ?dbpHypernym ?dbpComment ?dbpDeathPlace
        where
        { bind (<http://dbpedia.org/resource/Eltham> as ?dbpDeathPlace)
          service <http://DBpedia.org/sparql>
        { select ?dbpHypernym ?dbpComment ?dbpDeathPlace
        where
        {
        <http://dbpedia.org/resource/John_Lilburne>
            <http://purl.org/linguistics/gold/hypernym> ?dbpHypernym ;
            <http://www.w3.org/2000/01/rdf-schema#comment> ?dbpComment ;
            <http://dbpedia.org/ontology/deathPlace> ?dbpDeathPlace .

        } }  } limit 2'''
        results = g.query(q)
>       assert len(results) == 2
E       assert 0 == 2
E        +  where 0 = len(<rdflib.plugins.sparql.processor.SPARQLResult object at 0x7f814bd88820>)

test/test_sparql_service.py:42: AssertionError
_________________________________________________________________________ test_service_with_values _________________________________________________________________________

    def test_service_with_values():
        g = Graph()
        q = '''select ?dbpHypernym ?dbpComment ?dbpDeathPlace
        where
        { values (?dbpHypernym ?dbpDeathPlace) {(<http://dbpedia.org/resource/Leveller> <http://dbpedia.org/resource/London>) (<http://dbpedia.org/resource/Leveller> <http://dbpedia.org/resource/Eltham>)}
          service <http://DBpedia.org/sparql>
        { select ?dbpHypernym ?dbpComment ?dbpDeathPlace
        where
        {
        <http://dbpedia.org/resource/John_Lilburne>
            <http://purl.org/linguistics/gold/hypernym> ?dbpHypernym ;
            <http://www.w3.org/2000/01/rdf-schema#comment> ?dbpComment ;
            <http://dbpedia.org/ontology/deathPlace> ?dbpDeathPlace .

        } }  } limit 2'''
        results = g.query(q)
>       assert len(results) == 2
E       assert 0 == 2
E        +  where 0 = len(<rdflib.plugins.sparql.processor.SPARQLResult object at 0x7f814be60a90>)

test/test_sparql_service.py:64: AssertionError
============================================================================= warnings summary =============================================================================
test/test_conjunctive_graph.py:49
  test/test_conjunctive_graph.py:49: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_graph_ids will be ignored
    def test_graph_ids():

test/test_conneg.py:34
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_conneg.py:34: PytestCollectionWarning: cannot collect test class 'TestHTTPHandler' because it has a __init__ constructor (from: test/test_conneg.py)
    class TestHTTPHandler(BaseHTTPRequestHandler):

test/test_dawg.py:507
  test/test_dawg.py:507: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_dawg will be ignored
    def test_dawg():

test/test_evaluate_bind.py:8
  test/test_evaluate_bind.py:8: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_bind will be ignored
    def test_bind():

test/test_graph_formula.py:131
  test/test_graph_formula.py:131: PytestCollectionWarning: yield tests were removed in pytest 4.0 - testFormulaStores will be ignored
    def testFormulaStores():

test/test_n3_suite.py:34
  test/test_n3_suite.py:34: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_n3_writing will be ignored
    def test_n3_writing():

test/test_nquads_w3c.py:30
  test/test_nquads_w3c.py:30: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_nquads will be ignored
    def test_nquads(tests=None):

test/test_nt_w3c.py:30
  test/test_nt_w3c.py:30: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_nt will be ignored
    def test_nt(tests=None):

test/test_roundtrip.py:77
  test/test_roundtrip.py:77: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_cases will be ignored
    def test_cases():

test/test_roundtrip.py:96
  test/test_roundtrip.py:96: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_n3 will be ignored
    def test_n3():

test/test_sparql_agg_undef.py:26
  test/test_sparql_agg_undef.py:26: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_aggregates will be ignored
    def test_aggregates():

test/test_swap_n3.py:100
  test/test_swap_n3.py:100: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_cases will be ignored
    def test_cases():

test/test_trig_w3c.py:70
  test/test_trig_w3c.py:70: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_trig will be ignored
    def test_trig(tests=None):

test/test_turtle_w3c.py:59
  test/test_turtle_w3c.py:59: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_turtle will be ignored
    def test_turtle(tests=None):

test/test_hex_binary.py::HexBinaryTestCase::test_int
test/test_hex_binary.py::HexBinaryTestCase::test_int
test/test_hex_binary.py::HexBinaryTestCase::test_int
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_hex_binary.py:24: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(int(binascii.hexlify(bin_i), 16), i)

test/test_hex_binary.py::HexBinaryTestCase::test_int
test/test_hex_binary.py::HexBinaryTestCase::test_int
test/test_hex_binary.py::HexBinaryTestCase::test_int
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_hex_binary.py:29: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(str(l), hex_i)

test/test_hex_binary.py::HexBinaryTestCase::test_int
test/test_hex_binary.py::HexBinaryTestCase::test_int
test/test_hex_binary.py::HexBinaryTestCase::test_int
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_hex_binary.py:30: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(int(hex_i, 16), i)

test/test_hex_binary.py::HexBinaryTestCase::test_int
test/test_hex_binary.py::HexBinaryTestCase::test_int
test/test_hex_binary.py::HexBinaryTestCase::test_int
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_hex_binary.py:34: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(int(l, 16), i)

test/test_hex_binary.py::HexBinaryTestCase::test_int
test/test_hex_binary.py::HexBinaryTestCase::test_int
test/test_hex_binary.py::HexBinaryTestCase::test_int
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_hex_binary.py:35: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(int(str(l), 16), i)

test/test_hex_binary.py::HexBinaryTestCase::test_unicode
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_hex_binary.py:43: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(b_str1.decode('utf-8'), str1)

test/test_hex_binary.py::HexBinaryTestCase::test_unicode
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_hex_binary.py:47: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(str(l1), hex_str1)

test/test_hex_binary.py::HexBinaryTestCase::test_unicode
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_hex_binary.py:53: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(b_str1, b_str1b)

test/test_hex_binary.py::HexBinaryTestCase::test_unicode
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_hex_binary.py:54: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(b_str1b.decode('utf-8'), str1)

test/test_hex_binary.py::HexBinaryTestCase::test_unicode
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_hex_binary.py:58: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(str(l1b), hex_str1)

test/test_literal.py::TestParseBoolean::testNonFalseBoolean
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/rdflib/term.py:1393: DeprecationWarning: Parsing weird boolean, 'abcd' does not map to True or False
    warnings.warn('Parsing weird boolean, % r does not map to True or False' % value, category = DeprecationWarning)

test/test_literal.py::TestParseBoolean::testNonFalseBoolean
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/rdflib/term.py:1393: DeprecationWarning: Parsing weird boolean, '10' does not map to True or False
    warnings.warn('Parsing weird boolean, % r does not map to True or False' % value, category = DeprecationWarning)

test/test_rdf_lists.py::OWLCollectionTest::testCollectionRDFXML
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/rdflib/plugins/serializers/rdfxml.py:270: UserWarning: Assertions on rdflib.term.BNode('Nefd8a2eca82f4de090730fa6fb02506f') other than RDF.first and RDF.rest are ignored ... including RDF.List
    self.predicate(predicate, object, depth + 1)

test/test_trig.py::TestTrig::testPrefixes
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_trig.py:178: DeprecationWarning: Please use assertTrue instead.
    self.assert_(b('ns2: <http://ex.org/docs/') in data, data)

test/test_trig.py::TestTrig::testPrefixes
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_trig.py:179: DeprecationWarning: Please use assertTrue instead.
    self.assert_(b('<ns2:document1>') not in data, data)

test/test_trig.py::TestTrig::testPrefixes
  /home/tkloczko/rpmbuild/BUILD/rdflib-5.0.0/test/test_trig.py:180: DeprecationWarning: Please use assertTrue instead.
    self.assert_(b('ns2:document1') in data, data)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
SKIPPED [1] test/test_issue190.py:57: unittest.case.SkipTest: Known issue, with newlines in text
SKIPPED [1] test/test_issue200.py:12: unittest.case.SkipTest: No os.fork() and/or os.pipe() on this platform, skipping
SKIPPED [1] test/test_sparqlupdatestore.py:336: unittest.case.SkipTest: http://localhost:3031 is unavailable.
SKIPPED [1] test/test_dataset.py:125: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_dataset.py:80: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_dataset.py:145: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] ../../../../../usr/lib/python3.8/site-packages/_pytest/unittest.py:355: couldn't find networkx
SKIPPED [1] ../../../../../usr/lib/python3.8/site-packages/_pytest/unittest.py:355: couldn't find graph_tool
SKIPPED [1] test/test_graph.py:79: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph.py:137: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph.py:182: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph.py:214: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph.py:82: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph.py:149: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph.py:86: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph_context.py:112: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph_context.py:102: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph_context.py:172: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph_context.py:135: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph_context.py:119: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph_context.py:115: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph_context.py:196: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph_context.py:186: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph_context.py:148: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_graph_context.py:202: Dependencies for store 'Sleepycat' not available!
SKIPPED [1] test/test_trig.py:121: skipped until 5.0
XFAIL test/test_conjunctive_graph.py::test_graph_ids
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_graph_ids will be ignored
XFAIL test/test_dawg.py::test_dawg
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_dawg will be ignored
XFAIL test/test_evaluate_bind.py::test_bind
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_bind will be ignored
XFAIL test/test_graph_formula.py::testFormulaStores
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - testFormulaStores will be ignored
XFAIL test/test_n3_suite.py::test_n3_writing
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_n3_writing will be ignored
XFAIL test/test_nquads_w3c.py::test_nquads
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_nquads will be ignored
XFAIL test/test_nt_w3c.py::test_nt
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_nt will be ignored
XFAIL test/test_roundtrip.py::test_cases
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_cases will be ignored
XFAIL test/test_roundtrip.py::test_n3
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_n3 will be ignored
XFAIL test/test_sparql_agg_undef.py::test_aggregates
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_aggregates will be ignored
XFAIL test/test_swap_n3.py::test_cases
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_cases will be ignored
XFAIL test/test_trig_w3c.py::test_trig
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_trig will be ignored
XFAIL test/test_turtle_w3c.py::test_turtle
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_turtle will be ignored
FAILED test/test_sparql_service.py::test_service - assert 0 == 2
FAILED test/test_sparql_service.py::test_service_with_bind - assert 0 == 2
FAILED test/test_sparql_service.py::test_service_with_values - assert 0 == 2
=================================================== 3 failed, 387 passed, 26 skipped, 13 xfailed, 40 warnings in 27.98s ====================================================
```
I've switched to pytest because it allows desellect excat units.
