### ISSUE TITLE
No plugin registered for (application/ld+json, <class 'rdflib.parser.Parser'>)

### ISSUE THREAD

**Issue by stigbd** [RDFLib/rdflib#1387]
When trying to parse json-ld data with `format="application/ld+json"`, I get a PluginException. 

Steps to reproduce:
```
>>> from rdflib import Graph
RDFLib Version: 6.0.0
>>> data = """
{
    "@context": {"@vocab": "http://schema.org/"},
    "@graph": [
        { "@id": "http://example.org/data#jdoe",
          "name": "John"
        },
        { "@id": "http://example.org/data#janedoe",
          "name": "Jane"
        },
        { "@id": "http://example.org/data#metadata",
          "@graph": [
              { "@id": "http://example.org/data",
                "creator": "http://example.org/data#janedoe"
              }
          ]
        }
    ]
}
"""
>>> g = Graph()
>>> g.parse(data=data, format="application/ld+json")
Traceback (most recent call last):
  File "/home/stigbd/.cache/pypoetry/virtualenvs/concepttordf-GTEa4rMt-py3.8/lib/python3.8/site-packages/rdflib/plugin.py", line 107, in get
    p = _plugins[(name, kind)]
KeyError: ('application/ld+json', <class 'rdflib.parser.Parser'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stigbd/.cache/pypoetry/virtualenvs/concepttordf-GTEa4rMt-py3.8/lib/python3.8/site-packages/rdflib/graph.py", line 1209, in parse
    parser = plugin.get(format, Parser)()
  File "/home/stigbd/.cache/pypoetry/virtualenvs/concepttordf-GTEa4rMt-py3.8/lib/python3.8/site-packages/rdflib/plugin.py", line 109, in get
    raise PluginException("No plugin registered for (%s, %s)" % (name, kind))
rdflib.plugin.PluginException: No plugin registered for (application/ld+json, <class 'rdflib.parser.Parser'>)
```
When doing `g.parse(data=data, format="json-ld")` everything works fine.

It is my expectation that "application/ld+json" should be treated equivalently to "json-ld".

**Comment by stigbd** [comment]
I believe the following line contains the bug:
https://github.com/RDFLib/rdflib/blob/038af4547e799845e08986867b24acafcbe72d48/rdflib/plugin.py#L208

Here name is given as `application/json+ld`, whereas the correct is `application/ld+json`.
