### ISSUE TITLE
nquads should serialize non-context aware stores also.

### ISSUE THREAD

**Issue by aucampia** [RDFLib/rdflib#1892]
While writing some tests I noticed:

```
================================================================================= FAILURES ==================================================================================
____________________________________________________________ test_serialize_parse[nquads-TRIPLE-BINARY_IO-None] _____________________________________________________________
Traceback (most recent call last):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/test/test_serializers/test_serializer.py", line 383, in test_serialize_parse
    serialize_result = graph.serialize(
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/graph.py", line 1127, in serialize
    serializer = plugin.get(format, Serializer)(self)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/plugins/serializers/nquads.py", line 15, in __init__
    raise Exception(
Exception: NQuads serialization only makes sense for context-aware stores!
========================================================================== short test summary info ==========================================================================
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[nquads-TRIPLE-BINARY_IO-None] - Exception: NQuads serialization only makes sense for context-aware s...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================= 1 failed, 10 xfailed in 0.13s =======================================================================
```

I don't see why this should be the case, nquads should just encode everything with the default context, which will result in something that looks like ntriples.

**Comment by aucampia** [comment]
```
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[nquads-TRIPLE-None-None] - Exception: NQuads serialization only makes sense for context-aware stores!
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[nquads-TRIPLE-None-utf-8] - Exception: NQuads serialization only makes sense for context-aware stores!
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[nquads-TRIPLE-PATH-None] - Exception: NQuads serialization only makes sense for context-aware stores!
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[nquads-TRIPLE-PATH-utf-8] - Exception: NQuads serialization only makes sense for context-aware stores!
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[nquads-TRIPLE-STR_PATH-None] - Exception: NQuads serialization only makes sense for context-aware st...
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[nquads-TRIPLE-STR_PATH-utf-8] - Exception: NQuads serialization only makes sense for context-aware s...
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[nquads-TRIPLE-PURE_PATH-None] - Exception: NQuads serialization only makes sense for context-aware s...
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[nquads-TRIPLE-PURE_PATH-utf-8] - Exception: NQuads serialization only makes sense for context-aware ...
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[nquads-TRIPLE-BINARY_IO-None] - Exception: NQuads serialization only makes sense for context-aware s...
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[nquads-TRIPLE-BINARY_IO-utf-8] - Exception: NQuads serialization only makes sense for context-aware ...
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[trix-TRIPLE-None-None] - Exception: TriX serialization only makes sense for context-aware stores
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[trix-TRIPLE-None-utf-8] - Exception: TriX serialization only makes sense for context-aware stores
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[trix-TRIPLE-PATH-None] - Exception: TriX serialization only makes sense for context-aware stores
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[trix-TRIPLE-PATH-utf-8] - Exception: TriX serialization only makes sense for context-aware stores
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[trix-TRIPLE-STR_PATH-None] - Exception: TriX serialization only makes sense for context-aware stores
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[trix-TRIPLE-STR_PATH-utf-8] - Exception: TriX serialization only makes sense for context-aware stores
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[trix-TRIPLE-PURE_PATH-None] - Exception: TriX serialization only makes sense for context-aware stores
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[trix-TRIPLE-PURE_PATH-utf-8] - Exception: TriX serialization only makes sense for context-aware stores
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[trix-TRIPLE-BINARY_IO-None] - Exception: TriX serialization only makes sense for context-aware stores
FAILED test/test_serializers/test_serializer.py::test_serialize_parse[trix-TRIPLE-BINARY_IO-utf-8] - Exception: TriX serialization only makes sense for context-aware stores
```

**Comment by gjhiggins** [comment]
It's a consequence of the implementation of looping over the store contexts in https://github.com/RDFLib/rdflib/blob/eba13739e1d24b3e52697a1ec9545a361116951f/rdflib/plugins/serializers/nquads.py#L37

```py
        for context in self.store.contexts():
            for triple in context:
                stream.write(
                    _nq_row(triple, context.identifier).encode(encoding, "replace")
                )
```

**Comment by gabrielemidulla** [comment]
PR: https://github.com/RDFLib/rdflib/pull/3535
