### ISSUE TITLE
Serializer gets stuck with a large dataset and a simple query. 

### ISSUE THREAD

**Issue by GreenfishK** [RDFLib/rdflib#2216]
I am parsing an RDF datasaet of 485.179 triples into rdflib's Graph(), querying it with a simple SPARQL query and then trying to serialize it as csv. However, the serializer takes forever. I tried to pinpoint the issue and it seems to be coupled to the bindings of rdflib.plugins.sparql.processor.SPARQLResult, as even trying to print them gets stuck.

the dataset can be obtained from here: https://aic.ai.wu.ac.at/qadlod/bear/BEAR_C/datasets/IC/alldata.IC.nt.tar.gz
Extract the tar archive and copy 1.nt into the same directory as where you run the code below

```
from rdflib import Graph
from rdflib.query import Result

graph = Graph()
graph.parse("1.nt")

query_text = """
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# version 01
Select *
{
    ?distr1 dcat:distribution ?dataset .
    ?distr1 dcat:mediaType "text/csv" .
    ?dataset rdf:type dcat:Dataset .
}

"""

print("Querying ...")
query_result = graph.query(query_text)
print("Saving results ...")
# Gets stuck
query_result.serialize("query_result.csv", format="csv")

# Trying to print just the bindings
# Gets stuck
print(query_result.bindings)
```

**Comment by kwisatz** [comment]
We're seeing a similar problem handling about 620 records (50.000 lines) and far less triples than in @GreenfishK's case.
At first I thought it would be an entropy problem since I saw lots of `getrandom()` calls through `strace` but entropy on our systems is fine.

I am not exactly sure how to go about debugging this, but what I can supply are stacktraces from our `KeyboardInterrupt`s. These are in no particular order and interrupted somewhere after 10 through 40 minutes of the code "just sitting there":

```bash
^CTraceback (most recent call last):
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 452, in <module>
    main(parser.parse_args())
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 129, in main
    update_cidoc_sources(login_instance, agents, args)
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 186, in update_cidoc_sources
    create_or_update(graph, person, login_instance, agents, args)
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 249, in create_or_update
    for item in get_value_from_cidoc(graph, subject, query, args):
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 289, in get_value_from_cidoc
    for item in result:
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/query.py", line 277, in __iter__
    for b in self._genbindings:
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 457, in <genexpr>
    return (row.project(project.PV) for row in res)
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 134, in evalLeftJoin
    for a in evalPart(ctx, join.p1):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 134, in evalLeftJoin
    for a in evalPart(ctx, join.p1):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 74, in evalBGP
    for x in evalBGP(c, bgp[1:]):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 74, in evalBGP
    for x in evalBGP(c, bgp[1:]):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 74, in evalBGP
    for x in evalBGP(c, bgp[1:]):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 55, in evalBGP
    c = ctx.push()
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/sparql.py", line 342, in push
    r = self.clone(Bindings(self.bindings))
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/sparql.py", line 256, in clone
    r = QueryContext(
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/sparql.py", line 251, in __init__
    self.now = datetime.datetime.now(isodate.tzinfo.UTC)
KeyboardInterrupt

---

^CTraceback (most recent call last):
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 452, in <module>
    main(parser.parse_args())
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 129, in main
    update_cidoc_sources(login_instance, agents, args)
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 186, in update_cidoc_sources
    create_or_update(graph, person, login_instance, agents, args)
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 249, in create_or_update
    for item in get_value_from_cidoc(graph, subject, query, args):
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 289, in get_value_from_cidoc
    for item in result:
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/query.py", line 277, in __iter__
    for b in self._genbindings:
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 457, in <genexpr>
    return (row.project(project.PV) for row in res)
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 134, in evalLeftJoin
    for a in evalPart(ctx, join.p1):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 134, in evalLeftJoin
    for a in evalPart(ctx, join.p1):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 74, in evalBGP
    for x in evalBGP(c, bgp[1:]):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 74, in evalBGP
    for x in evalBGP(c, bgp[1:]):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 74, in evalBGP
    for x in evalBGP(c, bgp[1:]):
  [Previous line repeated 1 more time]
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 53, in evalBGP
    for ss, sp, so in ctx.graph.triples((_s, _p, _o)):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/graph.py", line 421, in triples
    for (s, p, o), cg in self.__store.triples((s, p, o), context=self):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/memory.py", line 318, in triples
    enctriple = self.__encodeTriple(triplein)
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/memory.py", line 478, in __encodeTriple
    return tuple(map(self.__obj2id, triple))
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/memory.py", line 467, in __obj2id
    if obj not in self.__obj2int:
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/term.py", line 141, in __eq__
    def __eq__(self, other):
KeyboardInterrupt


---

^CTraceback (most recent call last):
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 452, in <module>
    main(parser.parse_args())
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 129, in main
    update_cidoc_sources(login_instance, agents, args)
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 186, in update_cidoc_sources
    create_or_update(graph, person, login_instance, agents, args)
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 249, in create_or_update
    for item in get_value_from_cidoc(graph, subject, query, args):
  File "/home/kwisatz/1024/projects/someproject/tool/./tool", line 289, in get_value_from_cidoc
    for item in result:
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/query.py", line 277, in __iter__
    for b in self._genbindings:
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 457, in <genexpr>
    return (row.project(project.PV) for row in res)
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 134, in evalLeftJoin
    for a in evalPart(ctx, join.p1):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 134, in evalLeftJoin
    for a in evalPart(ctx, join.p1):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 74, in evalBGP
    for x in evalBGP(c, bgp[1:]):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 74, in evalBGP
    for x in evalBGP(c, bgp[1:]):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 74, in evalBGP
    for x in evalBGP(c, bgp[1:]):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/sparql/evaluate.py", line 53, in evalBGP
    for ss, sp, so in ctx.graph.triples((_s, _p, _o)):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/graph.py", line 421, in triples
    for (s, p, o), cg in self.__store.triples((s, p, o), context=self):
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/memory.py", line 358, in <genexpr>
    return ((self.__decodeTriple(enctriple), self.__contexts(enctriple))
  File "/home/kwisatz/.local/lib/python3.9/site-packages/rdflib/plugins/memory.py", line 483, in __decodeTriple
    return tuple(map(self.__int2obj.get, enctriple))
KeyboardInterrupt
```

It's not like it's hogging memory or CPU, it's just apparently not doing anything.

**Comment by aucampia** [comment]
@GreenfishK when you say gets stuck, does it get into a state where it won't complete, or does it just take prohibitively long?

**Comment by GreenfishK** [comment]
> @GreenfishK when you say gets stuck, does it get into a state where it won't complete, or does it just take prohibitively long?

Sorry for the ambiguous expression. What I mean by it is that it won't complete. At least I haven't seen it completing. Maybe if I waited a couple of days longer...

**Comment by kwisatz** [comment]
Okay… this has been running for over 13 hours now and we're still at the first node of more than 620. I'll abort this profiling because I doubt it will finish within this century. 

We will look into structuring our graph differently, perhaps using [multi-graphs](https://rdflib.readthedocs.io/en/stable/intro_to_parsing.html#working-with-multi-graphs) if we can make that work for us. I imagine that would allow us to run queries within a single node and hopefully significantly speed it up.

**Comment by kwisatz** [comment]
For the record, we switched to a multi-graph (`Dataset`) approach and the queries are now running just fine. We're handling the 629 records in roughly 2 minutes.
