### ISSUE TITLE
Warning When handling Hex Values

### ISSUE THREAD

**Issue by tobiasschweizer** [RDFLib/rdflib#2496]
Hi there,

I am dealing with some warnings related to hex values.

I don't understand whether this is something which is wrong in the data or a problem in rdflib itself.
Could it be related to the leading `#` in the data? This seems redundant since the data is annotated as hex.

Any feedback is appreciated! Thanks.

Data (snippet):

```xml
    <edm:WebResource
            rdf:about="https://mmb-web.adlibhosting.com/ais6/webapi/wwwopac.ashx?command=getcontent&amp;server=images&amp;value=/Voorwerpen%20Adlib/0-9000/V00000-MT51.jpg">
        <ebucore:hasMimeType>image/jpeg</ebucore:hasMimeType>
        <ebucore:fileByteSize rdf:datatype="http://www.w3.org/2001/XMLSchema#long">100742</ebucore:fileByteSize>
        <ebucore:width rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">900</ebucore:width>
        <ebucore:height rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">675</ebucore:height>
        <edm:hasColorSpace>sRGB</edm:hasColorSpace>
        <edm:componentColor rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">#696969</edm:componentColor>
        <edm:componentColor rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">#C0C0C0</edm:componentColor>
        <edm:componentColor rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">#2F4F4F</edm:componentColor>
        <edm:componentColor rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">#000000</edm:componentColor>
        <edm:componentColor rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">#808080</edm:componentColor>
        <edm:componentColor rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">#A9A9A9</edm:componentColor>
        <ebucore:orientation rdf:datatype="http://www.w3.org/2001/XMLSchema#string">landscape</ebucore:orientation>
    </edm:WebResource>
```

Warnings:

> Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#hexBinary, Converter=<function _unhexlify at 0x108171280>
> Traceback (most recent call last):
>   File "env/lib/python3.9/site-packages/rdflib/term.py", line 2084, in _castLexicalToPython
>     return conv_func(lexical)  # type: ignore[arg-type]
>   File "env/lib/python3.9/site-packages/rdflib/term.py", line 1680, in _unhexlify
>     return unhexlify(value)
> binascii.Error: Odd-length string
> Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#hexBinary, Converter=<function _unhexlify at 0x108171280>
> Traceback (most recent call last):
>   File "env/lib/python3.9/site-packages/rdflib/term.py", line 2084, in _castLexicalToPython
>     return conv_func(lexical)  # type: ignore[arg-type]
>   File "env/lib/python3.9/site-packages/rdflib/term.py", line 1680, in _unhexlify
>     return unhexlify(value)
> binascii.Error: Odd-length string
> Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#hexBinary, Converter=<function _unhexlify at 0x108171280>
> Traceback (most recent call last):
>   File "env/lib/python3.9/site-packages/rdflib/term.py", line 2084, in _castLexicalToPython
>     return conv_func(lexical)  # type: ignore[arg-type]
>   File "env/lib/python3.9/site-packages/rdflib/term.py", line 1680, in _unhexlify
>     return unhexlify(value)
> binascii.Error: Odd-length string
> Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#hexBinary, Converter=<function _unhexlify at 0x108171280>
> Traceback (most recent call last):
>   File "env/lib/python3.9/site-packages/rdflib/term.py", line 2084, in _castLexicalToPython
>     return conv_func(lexical)  # type: ignore[arg-type]
>   File "env/lib/python3.9/site-packages/rdflib/term.py", line 1680, in _unhexlify
>     return unhexlify(value)
> binascii.Error: Odd-length string
> Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#hexBinary, Converter=<function _unhexlify at 0x108171280>
> Traceback (most recent call last):
>   File "env/lib/python3.9/site-packages/rdflib/term.py", line 2084, in _castLexicalToPython
>     return conv_func(lexical)  # type: ignore[arg-type]
>   File "env/lib/python3.9/site-packages/rdflib/term.py", line 1680, in _unhexlify
>     return unhexlify(value)
> binascii.Error: Odd-length string
> Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#hexBinary, Converter=<function _unhexlify at 0x108171280>
> Traceback (most recent call last):
>   File "env/lib/python3.9/site-packages/rdflib/term.py", line 2084, in _castLexicalToPython
>     return conv_func(lexical)  # type: ignore[arg-type]
>   File "env/lib/python3.9/site-packages/rdflib/term.py", line 1680, in _unhexlify
>     return unhexlify(value)
> binascii.Error: Odd-length string

Steps to reproduce:

- download [out-01.xml.txt](https://github.com/RDFLib/rdflib/files/12077377/out-01.xml.txt)
- rename to xml (remove `txt` extension)
- run from REPL:
```python
>>> from rdflib import Graph
>>> g = Graph()
>>> g.parse('out-01.xml')
```

I originally got this data from an OAI-PMH endpoint with embedded RDF/XML, see https://api.europeana.eu/oai/record?verb=ListRecords&set=79&metadataPrefix=edm.

**Comment by aucampia** [comment]
@tobiasschweizer I would test the file with Jena's riot, and if Jena parses it without objections, it likely is a problem with RDFLib.

**Comment by tobiasschweizer** [comment]
That's great, thanks. I think once I had removed the leading `#` it worked fine. However, I am not sure whether the `#` should be there in the data or not. I found this example where it is not present: https://www.w3.org/TR/swbp-xsch-datatypes/#sec-values-examples ("hexBinary and base64Binary"). So maybe the data source is wrong.
