### ISSUE TITLE
7.1.0: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [RDFLib/rdflib#2936]
Sphinx 8.1.3 and looks like it is something wrong with building documentation.
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v8.1.3
loading translations [en]... done
making output directory... done
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/rdflib.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/rdflib.extras.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/rdflib.namespace.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/rdflib.plugins.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/rdflib.plugins.parsers.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/rdflib.plugins.serializers.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/rdflib.plugins.shared.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/rdflib.plugins.shared.jsonld.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/rdflib.plugins.sparql.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/rdflib.plugins.sparql.results.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/rdflib.plugins.stores.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/rdflib.tools.rst.
Creating file /home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/docs/apidocs/modules.rst.
loading intersphinx inventory 'python' from https://docs.python.org/3.8/objects.inv ...
myst v4.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=set(), disable_syntax=[], all_links_external=False, links_external_new_tab=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_sort=True, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 43 added, 0 changed, 0 removed
reading sources... [  2%] CODE_OF_CONDUCT
reading sources... [  5%] CONTRIBUTING
reading sources... [  7%] apidocs/examples
reading sources... [  9%] apidocs/modules
reading sources... [ 12%] apidocs/rdflib
reading sources... [ 14%] apidocs/rdflib.extras
reading sources... [ 16%] apidocs/rdflib.namespace
WARNING: Cannot resolve forward reference in type annotations of "rdflib.query.Result.__iter__": name '_SubjectType' is not defined

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/util/typing.py", line 284, in restify
    elif _is_annotated_form(cls):
  File "/usr/lib/python3.10/site-packages/sphinx/util/typing.py", line 218, in _is_annotated_form
    or str(obj).startswith('typing.Annotated')
  File "/home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/rdflib/namespace/__init__.py", line 286, in __str__
    return str(cls._NS)
  File "/home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/rdflib/namespace/__init__.py", line 280, in __getattr__
    return cls.__getitem__(name)
  File "/home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/rdflib/namespace/__init__.py", line 258, in __getitem__
    raise AttributeError(
AttributeError: DefinedNamespace like object has no attribute '_NS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/util/inspect.py", line 483, in object_description
    s = repr(obj)
  File "/home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/rdflib/namespace/__init__.py", line 283, in __repr__
    return f"Namespace({str(cls._NS)!r})"
  File "/home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/rdflib/namespace/__init__.py", line 280, in __getattr__
    return cls.__getitem__(name)
  File "/home/tkloczko/rpmbuild/BUILD/rdflib-7.1.0/rdflib/namespace/__init__.py", line 258, in __getitem__
    raise AttributeError(
AttributeError: DefinedNamespace like object has no attribute '_NS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/cmd/build.py", line 514, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 381, in build
    self.builder.build_update()
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 355, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 385, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 502, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 567, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 630, in read_doc
    publisher.publish()
  File "/usr/lib/python3.10/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3.10/site-packages/sphinx/io.py", line 106, in read
    self.parse()
  File "/usr/lib/python3.10/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.10/site-packages/sphinx/parsers.py", line 85, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2790, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2790, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.10/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.10/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2369, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2106, in directive
    return self.run_directive(
  File "/usr/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2156, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autodoc/directive.py", line 139, in run
    documenter.generate(more_content=self.content)
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 973, in generate
    self.document_members(all_members)
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 847, in document_members
    documenter.generate(
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 1903, in generate
    return super().generate(more_content=more_content,
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 963, in generate
    self.add_directive_header(sig)
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 1742, in add_directive_header
    base_classes = [restify(cls, "smart") for cls in bases]
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 1742, in <listcomp>
    base_classes = [restify(cls, "smart") for cls in bases]
  File "/usr/lib/python3.10/site-packages/sphinx/util/typing.py", line 376, in restify
    return object_description(cls)
  File "/usr/lib/python3.10/site-packages/sphinx/util/inspect.py", line 485, in object_description
    raise ValueError from exc
ValueError

Exception occurred:
  File "/usr/lib/python3.10/site-packages/sphinx/util/inspect.py", line 485, in object_description
    raise ValueError from exc
ValueError
The full traceback has been saved in /tmp/sphinx-err-9o3flmkh.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by ashleysommer** [comment]
I don't think this is related to Sphinx 8 in particular, I started getting this same issue using Sphinx 7.4.2 while developing on the python 3.9+ branch that is now in `main`.
I already pushed a fix for it in #2964 (and backported to RDFLib 7.x in #2965).
