### ISSUE TITLE
UnicodeEncodeError on SPARQLError

### ISSUE THREAD

**Issue by sirex** [RDFLib/rdflib#446]
Here is code sample how to reproduce this error:

```python
import sys
import pprint
import rdflib

assert sys.version.startswith('2.7.6')
assert rdflib.__version__ == '4.0.1'

graph = rdflib.Graph()
graph.parse('http://dbpedia.org/resource/Metallica')
rows = graph.query('''
    SELECT DISTINCT ?p ?o
    WHERE {
        ?s ?p ?o .
        FILTER(lang(?o) = "" || lang(?o) = "en")
    }
''')

pprint.pprint(list(rows))
```

Running above, gives this:

```
Traceback (most recent call last):
  File "testme.py", line 18, in <module>
    pprint.pprint(list(rows))
  File "rdflib/query.py", line 238, in __len__
    return len(self.bindings)
  File "rdflib/query.py", line 178, in _get_bindings
    self._bindings += list(self._genbindings)
  File "rdflib/plugins/sparql/evaluate.py", line 353, in evalDistinct
    for x in res:
  File "rdflib/plugins/sparql/evaluate.py", line 362, in <genexpr>
    return (row.project(project.PV) for row in res)
  File "rdflib/plugins/sparql/evaluate.py", line 153, in evalFilter
    if _ebv(part.expr, c.forget(ctx)):
  File "rdflib/plugins/sparql/evalutils.py", line 50, in _ebv
    return EBV(expr.eval(ctx))
  File "rdflib/plugins/sparql/parserutils.py", line 194, in eval
    return self._evalfn(ctx)
  File "rdflib/plugins/sparql/operators.py", line 823, in ConditionalOrExpression
    expr = e.expr
  File "rdflib/plugins/sparql/parserutils.py", line 173, in __getattr__
    return self[a]
  File "rdflib/plugins/sparql/parserutils.py", line 163, in __getitem__
    return self._value(OrderedDict.__getitem__(self, a))
  File "rdflib/plugins/sparql/parserutils.py", line 158, in _value
    return value(self.ctx, val, variables)
  File "rdflib/plugins/sparql/parserutils.py", line 62, in value
    return val.eval(ctx)  # recurse?
  File "rdflib/plugins/sparql/parserutils.py", line 194, in eval
    return self._evalfn(ctx)
  File "rdflib/plugins/sparql/operators.py", line 783, in RelationalExpression
    raise SPARQLError('I cannot compare this non-node: %s' % expr)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 61-69: ordinal not in range(128)
```

I got same error on fresh `master` version.

**Comment by joernhees** [comment]
verified on rdflib 4.1.2

@gromgull :
debugging tells me that `expr` actually is another `SPARQLError` exception instead of a node...
```
ipdb> expr
SPARQLError(u'Non-literal passed as string: http://ka.dbpedia.org/resource/\u10db\u10d4\u10e2\u10d0\u10da\u10d8\u10d9\u10d0',)
```

suspecting someone actually returns a `SPARQLError` rather than raising it i find https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/sparql/parserutils.py#L196 . It excepts a `SPARQLError` but then returns it... should it maybe re-`raise` it?

Another problem is that the `UnicodeEncodeError` actually comes from https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/sparql/operators.py#L783 or https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/sparql/operators.py#L881 ... thing is that `"... %s .." % s` is used in various places where `u"... %s ..." % s` should probably be used, no?

**Comment by sirex** [comment]
http://python-future.org/unicode_literals.html
