### ISSUE TITLE
Cannot load turtle file using Graph.Parse

### ISSUE THREAD

**Issue by ChemSem** [RDFLib/rdflib#505]
I'm trying to parse the .ttl file using Parse like so:
g.parse(urn,format="turtle")

and it fails with the message:

Traceback (most recent call last):
  File "csi_7.py", line 59, in <module>
    ba=g.parse(urn,format="turtle")
  File "c:\python27\lib\site-packages\rdflib-4.2.0-py2.7.egg\rdflib\graph.py", line 1033, in parse
    parser.parse(source, self, **args)
  File "c:\python27\lib\site-packages\rdflib-4.2.0-py2.7.egg\rdflib\plugins\parsers\notation3.py", line 1870, in parse
    p.loadStream(source.getByteStream())
  File "c:\python27\lib\site-packages\rdflib-4.2.0-py2.7.egg\rdflib\plugins\parsers\notation3.py", line 434, in loadStream
    return self.loadBuf(stream.read())    # Not ideal
  File "c:\python27\lib\site-packages\rdflib-4.2.0-py2.7.egg\rdflib\plugins\parsers\notation3.py", line 440, in loadBuf
    self.feed(buf)
  File "c:\python27\lib\site-packages\rdflib-4.2.0-py2.7.egg\rdflib\plugins\parsers\notation3.py", line 470, in feed
    "expected directive or statement")
  File "c:\python27\lib\site-packages\rdflib-4.2.0-py2.7.egg\rdflib\plugins\parsers\notation3.py", line 1615, in BadSyntax
    raise BadSyntax(self._thisDoc, self.lines, argstr, i, msg)
rdflib.plugins.parsers.notation3.BadSyntax: at line 1 of <>:
Bad syntax (expected directive or statement) at ^ in:
"^@

Any ideas what this might mean?

**Comment by joernhees** [comment]
it looks as if the file you're trying to parse is broken, can you post the head of it?
