### ISSUE TITLE
pyparsing 2.1.2 broken on py3.4

### ISSUE THREAD

**Issue by xrotwang** [RDFLib/rdflib#627]
The current version of pyparsing, 2.1.2, is broken on python 3.4 (see below). Thus, fresh installs of rdflib are likewise. AFAICT the maintainers of pyparsing have been notified, but rddflib may still want to make sure, pyparsing != 2.1.2 is required upon install.

When installing from the wheel, installation works, but import doesn't:
```python
$ pip install rdflib
...
Successfully installed rdflib isodate pyparsing
Cleaning up...
$ python
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyparsing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shh.mpg.de/forkel/venvs/testclld/lib/python3.4/site-packages/pyparsing.py", line 3478, in <module>
    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
  File "/home/shh.mpg.de/forkel/venvs/testclld/lib/python3.4/site-packages/pyparsing.py", line 948, in setParseAction
    self.parseAction = list(map(_trim_arity, list(fns)))
  File "/home/shh.mpg.de/forkel/venvs/testclld/lib/python3.4/site-packages/pyparsing.py", line 808, in _trim_arity
    this_line = extract_stack()[-1]
  File "/home/shh.mpg.de/forkel/venvs/testclld/lib/python3.4/site-packages/pyparsing.py", line 793, in extract_stack
    return [(frame_summary.filename, frame_summary.lineno)]
AttributeError: 'tuple' object has no attribute 'filename'
```

Installing from source fails:
```
$ pip install https://pypi.python.org/packages/90/f5/8ca95e67983119f06326073e7ca3f0ce4325866a1358fab449a8f695dd52/pyparsing-2.1.2.zip#md5=3ebe0138a07d43eded7448388808730b
Downloading/unpacking https://pypi.python.org/packages/90/f5/8ca95e67983119f06326073e7ca3f0ce4325866a1358fab449a8f695dd52/pyparsing-2.1.2.zip
  Downloading pyparsing-2.1.2.zip (1.3MB): 1.3MB downloaded
  Running setup.py (path:/tmp/pip-j3rwzfxl-build/setup.py) egg_info for package from https://pypi.python.org/packages/90/f5/8ca95e67983119f06326073e7ca3f0ce4325866a1358fab449a8f695dd52/pyparsing-2.1.2.zip
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-j3rwzfxl-build/setup.py", line 9, in <module>
        from pyparsing import __version__ as pyparsing_version
      File "/tmp/pip-j3rwzfxl-build/pyparsing.py", line 3478, in <module>
        _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
      File "/tmp/pip-j3rwzfxl-build/pyparsing.py", line 948, in setParseAction
        self.parseAction = list(map(_trim_arity, list(fns)))
      File "/tmp/pip-j3rwzfxl-build/pyparsing.py", line 808, in _trim_arity
        this_line = extract_stack()[-1]
      File "/tmp/pip-j3rwzfxl-build/pyparsing.py", line 793, in extract_stack
        return [(frame_summary.filename, frame_summary.lineno)]
    AttributeError: 'tuple' object has no attribute 'filename'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-j3rwzfxl-build/setup.py", line 9, in <module>

    from pyparsing import __version__ as pyparsing_version

  File "/tmp/pip-j3rwzfxl-build/pyparsing.py", line 3478, in <module>

    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])

  File "/tmp/pip-j3rwzfxl-build/pyparsing.py", line 948, in setParseAction

    self.parseAction = list(map(_trim_arity, list(fns)))

  File "/tmp/pip-j3rwzfxl-build/pyparsing.py", line 808, in _trim_arity

    this_line = extract_stack()[-1]

  File "/tmp/pip-j3rwzfxl-build/pyparsing.py", line 793, in extract_stack

    return [(frame_summary.filename, frame_summary.lineno)]

AttributeError: 'tuple' object has no attribute 'filename'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-j3rwzfxl-build
```

**Comment by joernhees** [comment]
thanks for the heads up, will have a look...

**Comment by xrotwang** [comment]
pyparsing 2.1.3 fixes the problem (see the [CHANGELOG](https://sourceforge.net/p/pyparsing/code/HEAD/tree/trunk/src/CHANGES)).

**Comment by joernhees** [comment]
ok, i guess then there's no real action necessary from our side...
