### ISSUE TITLE
Parsing error on some SPARQL queries

### ISSUE THREAD

**Issue by Tpt** [RDFLib/rdflib#765]
The parsing of queries like the following ones raises the error: "postParse2() missing 1 required positional argument: 'tokenList'". 

Example of failing queries:
```
SELECT DISTINCT ?x WHERE {
	BIND(<http://foo/bar> AS ?x)
}
```

```
SELECT DISTINCT ?s ?p ?result2 WHERE {
	BIND(<http://schema.org/actor> AS ?p)
	BIND(<http://foo/bar> AS ?s)
	?s ?p ?result2 .
}
```

```
Backtrace:
Traceback (most recent call last):
  File "/foo/__init__.py", line 164, in evaluate_term
    results = self._graph.query(query)
  File "Library/Python/3.6/lib/python/site-packages/rdflib/graph.py", line 1089, in query
    query_object, initBindings, initNs, **kwargs))
  File "Library/Python/3.6/lib/python/site-packages/rdflib/plugins/sparql/processor.py", line 74, in query
    parsetree = parseQuery(strOrQuery)
  File "Library/Python/3.6/lib/python/site-packages/rdflib/plugins/sparql/parser.py", line 1058, in parseQuery
    return Query.parseString(q, parseAll=True)
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 3983, in parseImpl
    loc, tokens = self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 1405, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/usr/local/lib/python3.6/site-packages/pyparsing.py", line 1049, in wrapper
    ret = func(*args[limit[0]:])
TypeError: postParse2() missing 1 required positional argument: 'tokenList'
```

**Comment by Tpt** [comment]
It seems that this error is caused by the SPARQL parser that is not thread safe. It's probably an expected behaviour.

**Comment by gromgull** [comment]
Yeah, I am afraid pyparsing is not threadsafe.

**Comment by white-gecko** [comment]
With the QuitStore we sometime experience this issue as well. @Tpt did you see this error in combination with UWSGI?

**Comment by Tpt** [comment]
I never used UWSGI with rdflib. But, because it's a concurrency issue, it's likely to append with some UWSGI runners.

**Comment by mielvds** [comment]
anyway you can mitigate this error?

**Comment by white-gecko** [comment]
I guess #1282 is the current issue to follow. (Also in #1370 pyparsing was updated from pyparsing2 to pyparsing3, but there does not appear to be any changes regarding the threadsafety: https://pyparsing-docs.readthedocs.io/en/latest/whats_new_in_3_0_0.html)

**Comment by yuha0lin** [comment]
I also encountered this problem. Can I think that the thread safety problem has not been solved yet?<img width="588" alt="image" src="https://github.com/user-attachments/assets/cda99d7f-9753-4f33-bf21-78ab34b7a2f0" />
