### ISSUE TITLE
rdflib.tools.graphisomorphism doesn't work

### ISSUE THREAD

**Issue by Aaronepower** [RDFLib/rdflib#812]
Hello, I was trying to use `rdflib.tools.graphisomorphism` and it repeatedly gives the following error when trying to use it from either the command line or as a module and directly using `IsomorphicTestableGraph`.

**Python Version:** 3.6
**System Version:** macOS Sierra/10.13.3

```
INFO:rdflib:RDFLib Version: 4.2.2
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/rdflib/tools/graphisomorphism.py", line 127, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/rdflib/tools/graphisomorphism.py", line 117, in main
    fn, format=options.inputFormat)
  File "/usr/local/lib/python3.6/site-packages/rdflib/graph.py", line 1043, in parse
    parser.parse(source, self, **args)
  File "/usr/local/lib/python3.6/site-packages/rdflib/plugins/parsers/nt.py", line 26, in parse
    parser.parse(f)
  File "/usr/local/lib/python3.6/site-packages/rdflib/plugins/parsers/ntriples.py", line 140, in parse
    self.parseline()
  File "/usr/local/lib/python3.6/site-packages/rdflib/plugins/parsers/ntriples.py", line 200, in parseline
    self.sink.triple(subject, predicate, object)
  File "/usr/local/lib/python3.6/site-packages/rdflib/plugins/parsers/nt.py", line 12, in triple
    self.graph.add((s, p, o))
  File "/usr/local/lib/python3.6/site-packages/rdflib/graph.py", line 397, in add
    self.__store.add((s, p, o), self, quoted=False)
  File "/usr/local/lib/python3.6/site-packages/rdflib/plugins/memory.py", line 248, in add
    self.__all_contexts.add(context)
TypeError: unhashable type: 'IsomorphicTestableGraph'
```

**Comment by ajnelson-nist** [comment]
I have encountered the same issue.

Python Version: 3.8
rdflib Version: 5.0.0

**Comment by gjhiggins** [comment]
Yes, using it from the command line does result in an unhashable type Exception. However, using `IsomorphicTestableGraph` directly works as expected:
```py
def test_isomorphic_graph_checker():
    from rdflib.tools.graphisomorphism import IsomorphicTestableGraph

    g1 = Graph()
    g1.add((michel, likes, pizza))
    g1.add((michel, likes, pizza))
    g1.add((tarek, likes, cheese))
    g1.add((tarek, likes, michel))
    g1.add((tarek, likes, pizza))

    # Same statements, different order
    g2 = Graph()
    g2.add((tarek, likes, pizza))
    g2.add((tarek, likes, cheese))
    g2.add((tarek, likes, michel))
    g2.add((michel, likes, pizza))
    g2.add((michel, likes, pizza))

    input1 = g1.serialize(format="ttl")

    input2 = g2.serialize(format="ttl")

    graph1 = IsomorphicTestableGraph().parse(data=input1, format="ttl")

    graph2 = IsomorphicTestableGraph().parse(data=input2, format="ttl")

    assert graph1 == graph2

    # Make the graphs differ
    g2.add((michel, likes, tarek))

    input2 = g2.serialize(format="ttl")

    graph1 = IsomorphicTestableGraph().parse(data=input1, format="ttl")

    graph2 = IsomorphicTestableGraph().parse(data=input2, format="ttl")

    assert graph1 != graph2
```

**Comment by gjhiggins** [comment]
And there's a fix for the command line: parking here in case it gets lost - `Graph`s aren't hashable but their identifier is ...
```patch
diff --git a/rdflib/tools/graphisomorphism.py b/rdflib/tools/graphisomorphism.py
index fbb31c0e..792ee371 100644
--- a/rdflib/tools/graphisomorphism.py
+++ b/rdflib/tools/graphisomorphism.py
@@ -95,17 +95,20 @@ def main():
   if options.stdin:
       graph = IsomorphicTestableGraph().parse(sys.stdin, format=options.inputFormat)
       graphs.append(graph)
-        graph2FName[graph] = "(STDIN)"
+        graph2FName[graph.identifier] = "(STDIN)"
   for fn in args:
       graph = IsomorphicTestableGraph().parse(fn, format=options.inputFormat)
       graphs.append(graph)
-        graph2FName[graph] = fn
+        graph2FName[graph.identifier] = fn
   checked = set()
   for graph1, graph2 in combinations(graphs, 2):
-        if (graph1, graph2) not in checked and (graph2, graph1) not in checked:
+        if (graph1.identifier, graph2.identifier) not in checked and (
+            graph2.identifier,
+            graph1.identifier,
+        ) not in checked:
           assert graph1 == graph2, "%s != %s" % (
-                graph2FName[graph1],
-                graph2FName[graph2],
+                graph2FName[graph1.identifier],
+                graph2FName[graph2.identifier],
           )


```
wfm
