### ISSUE TITLE
XML Parser should support OWL/XML

### ISSUE THREAD

**Issue by jimmccusker** [RDFLib/rdflib#814]
The detection should be when the OWL namespace is declared instead of the RDF namespace. In fact, the namespace should be what triggers RDF as well, since RDF can be embedded in other non RDF/XML documents as well.

On a practical note, it can be difficult to tell if someone has published RDF/XML vs OWL/XML from just the file extension. This should successfully parse, after this is implemented:

```python
import rdflib

ont_url = 'http://purl.obolibrary.org/obo/stato.owl'
file_format = rdflib.util.guess_format(ont_url)
g = rdflib.Graph()
g.parse(location=ont_url,format=file_format)
```

Currently, we get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/apps/satoru/venv/local/lib/python2.7/site-packages/rdflib/graph.py", line 1032, in parse
    parser.parse(source, self, **args)
  File "/apps/satoru/venv/local/lib/python2.7/site-packages/rdflib/plugins/parsers/rdfxml.py", line 579, in parse
    self._parser.parse(source)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/apps/satoru/venv/local/lib/python2.7/site-packages/rdflib/plugins/parsers/rdfxml.py", line 161, in endElementNS
    self.current.end(name, qname)
  File "/apps/satoru/venv/local/lib/python2.7/site-packages/rdflib/plugins/parsers/rdfxml.py", line 333, in node_element_end
    self.error("Repeat node-elements inside property elements: %s"%"".join(name))
  File "/apps/satoru/venv/local/lib/python2.7/site-packages/rdflib/plugins/parsers/rdfxml.py", line 187, in error
    raise ParserError(info + message)
rdflib.exceptions.ParserError: http://purl.obolibrary.org/obo/stato.owl:17:117: Repeat node-elements inside property elements: http://www.w3.org/2002/07/owl#Literal
```

**Comment by mwatts15** [comment]
@jimmccusker what exactly do you mean by "when the OWL namespace is declared instead of the RDF namespace"? Currently, the document you linked has both `xmlns:owl` and `xmlns:rdf` declared in the root element.

**Comment by mwatts15** [comment]
Also worth noting, the linked document is currently parsed without error by the RDF/XML parser with the current HEAD of the master branch. We don't have a distinct OWL format.

**Comment by jimmccusker** [comment]
It looks like this particular ontology transitioned over to rdf/xml. Here is the one that would have been loaded when I filed the bug:

https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/1.2/stato.owl

I've updated the issue to use the older version.

**Comment by gjhiggins** [comment]
The original of that ontology is ill-formed, several Literals contain unescaped double-quotes. There's a commented-out fix in 
Jean-Baptiste Lamy's [owlready2 owl2ntriples implementation](https://bitbucket.org/jibalamy/owlready2/src/26369f19626aaf0a10243d8c1489f50c9eb62629/owlxml_2_ntriples.py#lines-145) which I uncommented and with a bit of quick-and-dirty hacking I adapted his parser for use as an RDFLib plugin-parser for OWL/XML - which _does_ read the original ontology (ill-formed as it is) into an RDFLib Graph. Pro tem, I have it earmarked for the RDFLib Cookbook.
