### ISSUE TITLE
ERROR IN : g.load('C://Users//Parth//Downloads//eventkg_1.1.tar//data//output//events.nq',format="nquads")

### ISSUE THREAD

**Issue by parthrohilla** [RDFLib/rdflib#908]
THE FOLLOWING ERROR, WHILE I TRY TO LOAD DATA USING RDFLIB
-->g.load('C://Users//Parth//Downloads//eventkg_1.1.tar//data//output//events.nq',format="nquads")

Traceback (most recent call last):

  File "<ipython-input-13-1e766fb04eb4>", line 1, in <module>
    g.load('C://Users//Parth//Downloads//eventkg_1.1.tar//data//output//events.nq',format="nquads")

  File "C:\Users\Parth\Anaconda3\lib\site-packages\rdflib\graph.py", line 1050, in load
    self.parse(source, publicID, format)

  File "C:\Users\Parth\Anaconda3\lib\site-packages\rdflib\graph.py", line 1043, in parse
    parser.parse(source, self, **args)

  File "C:\Users\Parth\Anaconda3\lib\site-packages\rdflib\plugins\parsers\nquads.py", line 66, in parse
    raise ParseError("Invalid line (%s):\n%r" % (msg, __line))

ParseError: Invalid line (Subject must be uriref or nodeID):
'@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .'

**Comment by gjhiggins** [comment]
Error correctly raised, format specified does not match source format.
