### ISSUE TITLE
NTriples fails to parse URIs with only a scheme

### ISSUE THREAD

**Issue by chmod007** [RDFLib/rdflib#920]
>>> from rdflib import Graph
>>> g=Graph()
>>> g.parse(data='<a:> <b:> <c:> .', format='nt') # nquads also fails

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rdflib/graph.py", line 1039, in parse
    parser.parse(source, self, **args)
  File "/Library/Python/2.7/site-packages/rdflib/plugins/parsers/nt.py", line 26, in parse
    parser.parse(f)
  File "/Library/Python/2.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 142, in parse
    raise ParseError("Invalid line: %r" % self.line)
rdflib.plugins.parsers.ntriples.ParseError: Invalid line: u'<a:> <b:> <c:> .'

N3, by contrast, succeeds:

>>> g.parse(data='<a:> <b:> <c:> .', format='n3')

Fix is to change:
uriref = r'<([^:]+:[^\s"<>]+)>'
to:
uriref = r'<([^:]+:[^\s"<>]*)>'
in ntriples.py.

**Comment by nicholascar** [comment]
Addressed in PR #973

**Comment by nicholascar** [comment]
Fixed in PR #974

**Comment by white-gecko** [comment]
Fixed via 107ffb6467f813980dcccd1f652ccde6b97d8d32. (#974)
