### ISSUE TITLE
rdflib won't parse valid Turtle with slightly more complex class constraint

### ISSUE THREAD

**Issue by hansidm** [RDFLib/rdflib#934]
I am having trouble loading this sample Turtle:
```
@prefix myns: <http://purl.org/myns/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

myns:AClass a owl:Class ;
    rdfs:label "This is a class" ;
    rdfs:subClassOf prov:Activity,
                    prov:Plan, [
                        a owl:Restriction ;
                        owl:onProperty prov:wasAssociatedWith ;
                        owl:someValuesFrom [
                            a owl:Restriction ;
                            owl:onProperty prov:atLocation ;
                            owl:someValuesFrom prov:Location .
                        ]
                    ] .
```

with this code:
```
from rdflib import Graph

g = Graph()
g.parse("data.ttl", format="turtle")

len(g) # prints 2

import pprint
for stmt in g:
    pprint.pprint(stmt)
```

This is the error I get:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    g.parse("data.ttl", format="turtle")
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/graph.py", line 1043, in parse
    parser.parse(source, self, **args)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1870, in parse
    p.loadStream(source.getByteStream())
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 434, in loadStream
    return self.loadBuf(stream.read())    # Not ideal
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 440, in loadBuf
    self.feed(buf)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 466, in feed
    i = self.directiveOrStatement(s, j)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 487, in directiveOrStatement
    j = self.statement(argstr, i)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 725, in statement
    j = self.property_list(argstr, i, r[0])
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1086, in property_list
    i = self.objectList(argstr, j, objs)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1144, in objectList
    i = self.object(argstr, j + 1, res)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1406, in object
    j = self.subject(argstr, i, res)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 733, in subject
    return self.item(argstr, i, res)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 829, in item
    return self.path(argstr, i, res)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 837, in path
    j = self.nodeOrLiteral(argstr, i, res)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1431, in nodeOrLiteral
    j = self.node(argstr, i, res)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 911, in node
    i = self.property_list(argstr, j, subj)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1086, in property_list
    i = self.objectList(argstr, j, objs)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1134, in objectList
    i = self.object(argstr, i, res)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1406, in object
    j = self.subject(argstr, i, res)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 733, in subject
    return self.item(argstr, i, res)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 829, in item
    return self.path(argstr, i, res)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 837, in path
    j = self.nodeOrLiteral(argstr, i, res)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1431, in nodeOrLiteral
    j = self.node(argstr, i, res)
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 922, in node
    "']' expected")
  File "/Users/hensantos/test/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1615, in BadSyntax
    raise BadSyntax(self._thisDoc, self.lines, argstr, i, msg)
rdflib.plugins.parsers.notation3.BadSyntax: at line 16 of <>:
Bad syntax (']' expected) at ^ in:
"...b'                           owl:someValuesFrom prov:Location '^b'.\n                        ]\n                    ] .\n'"
```

And here is my `pip freeze` output:
```
isodate==0.6.0
pyparsing==2.4.2
rdflib==4.2.2
six==1.12.0
```

The Turtle file loads and displays fine in Protégé.
Any hints?

**Comment by tgbugs** [comment]
The `.` in `owl:someValuesFrom prov:Location .` should not be there.

**Comment by mwatts15** [comment]
@tgbugs is correct [blankNodePropertyList](https://www.w3.org/TR/turtle/#grammar-production-blankNodePropertyList) does not include a trailing "." -- that comes from [statement](https://www.w3.org/TR/turtle/#grammar-production-statement)

**Comment by nicholascar** [comment]
@tgbugs and @mwatts15 are correct: this is a user Turtle error, not an rdfllib error, so I'm closing this Issue.
