### ISSUE TITLE
Turtle parser fails with leading dot in decimal value

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/rdflib#999]
Input file `test.ttl`:
```
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

<http://qudt.org/vocab/unit/MilliM-PER-YR>
  a <http://qudt.org/schema/qudt/Unit> ;
  <http://qudt.org/schema/qudt/conversionMultiplier> .171e-11 ;
  <http://qudt.org/schema/qudt/conversionOffset> 0e+00 ;
  <http://qudt.org/schema/qudt/description> "0.001-fold of the SI base unit metre divided by the unit year" ;
  <http://qudt.org/schema/qudt/hasQuantityKind> <http://qudt.org/vocab/quantitykind/Velocity> ;
  <http://qudt.org/schema/qudt/iec61360Code> "0112/2///62720#UAA868" ;
  <http://qudt.org/schema/qudt/uneceCommonCode> "H66" ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
  rdfs:isDefinedBy <http://qudt.org/vocab/unit> ;
  rdfs:label "MilliM PER YR" ;
  <http://www.w3.org/2004/02/skos/core#prefLabel> "millimetre per year" ;
.
```
Traceback:
```
>>> from rdflib import Graph
INFO:rdflib:RDFLib Version: 4.2.2
>>> g = Graph().parse('test.ttl', format='turtle')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/rdflib/graph.py", line 1043, in parse
    parser.parse(source, self, **args)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1870, in parse
    p.loadStream(source.getByteStream())
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 434, in loadStream
    return self.loadBuf(stream.read())    # Not ideal
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 440, in loadBuf
    self.feed(buf)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 466, in feed
    i = self.directiveOrStatement(s, j)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 489, in directiveOrStatement
    return self.checkDot(argstr, j)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1159, in checkDot
    "expected '.' or '}' or ']' at end of statement")
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1615, in BadSyntax
    raise BadSyntax(self._thisDoc, self.lines, argstr, i, msg)
rdflib.plugins.parsers.notation3.BadSyntax: at line 5 of <>:
Bad syntax (expected '.' or '}' or ']' at end of statement) at ^ in:
"...b' ;\n  <http://qudt.org/schema/qudt/conversionMultiplier> .171'^b'e-11 ;\n  <http://qudt.org/schema/qudt/conversionOffset> 0e+0'..."
>>> exit()
```
The parser is having issue with this line in the input file: `<http://qudt.org/schema/qudt/conversionMultiplier> .171e-11 ;`

Not very familiar with the code but probably some additional checks are required in `directiveOrStatement()` or `checkDot()`.

**Comment by white-gecko** [comment]
Could you please test with the current 5.0.0rc1?

**Comment by gweis** [comment]
almost identical:

```
Python 3.7.5 (default, Oct 17 2019, 12:25:15) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdflib import Graph
RDFLib Version: 5.0.0rc1
>>> ttl = """prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
... 
... <http://qudt.org/vocab/unit/MilliM-PER-YR>
...   a <http://qudt.org/schema/qudt/Unit> ;
...   <http://qudt.org/schema/qudt/conversionMultiplier> .171e-11 ;
...   <http://qudt.org/schema/qudt/conversionOffset> 0e+00 ;
...   <http://qudt.org/schema/qudt/description> "0.001-fold of the SI base unit metre divided by the unit year" ;
...   <http://qudt.org/schema/qudt/hasQuantityKind> <http://qudt.org/vocab/quantitykind/Velocity> ;
...   <http://qudt.org/schema/qudt/iec61360Code> "0112/2///62720#UAA868" ;
...   <http://qudt.org/schema/qudt/uneceCommonCode> "H66" ;
...   rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
...   rdfs:isDefinedBy <http://qudt.org/vocab/unit> ;
...   rdfs:label "MilliM PER YR" ;
...   <http://www.w3.org/2004/02/skos/core#prefLabel> "millimetre per year" ;
... ."""
>>> Graph().parse(data=ttl, format="turtle")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/rdflib/graph.py", line 1072, in parse
    parser.parse(source, self, **args)
  File "/usr/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1888, in parse
    p.loadStream(source.getByteStream())
  File "/usr/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 444, in loadStream
    return self.loadBuf(stream.read())    # Not ideal
  File "/usr/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 450, in loadBuf
    self.feed(buf)
  File "/usr/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 476, in feed
    i = self.directiveOrStatement(s, j)
  File "/usr/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 499, in directiveOrStatement
    return self.checkDot(argstr, j)
  File "/usr/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1169, in checkDot
    "expected '.' or '}' or ']' at end of statement")
  File "/usr/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1625, in BadSyntax
    raise BadSyntax(self._thisDoc, self.lines, argstr, i, msg)
rdflib.plugins.parsers.notation3.BadSyntax: at line 5 of <>:
Bad syntax (expected '.' or '}' or ']' at end of statement) at ^ in:
"...b' ;\n  <http://qudt.org/schema/qudt/conversionMultiplier> .171'^b'e-11 ;\n  <http://qudt.org/schema/qudt/conversionOffset> 0e+0'..."
>>>
```

**Comment by nicholascar** [comment]
`.171e-11` is indeed a valid Turtle number from [1]:

```
[21] | DOUBLE | ::= | [+-]? ([0-9]+ '.' [0-9]* EXPONENT \|  '.' [0-9]+ EXPONENT \|  [0-9]+ EXPONENT)
```

So I guess we have to deal with it.

Annoys me the spec allows isomorphic variations; they just create more necessary software rules...

[1] https://www.w3.org/TR/turtle/#grammar-production-DOUBLE

**Comment by gweis** [comment]
The regexp in use covers this case https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/parsers/notation3.py#L352. 
It's just that the parser seems to see the `.` first.

**Comment by nicholascar** [comment]
@gweis thanks for the clarification! Makes is a bit more difficult to deal with. A PR from you or @edmondchuc would be great...

**Comment by white-gecko** [comment]
Is there any chance we can get this fixed for 5.0.0 release?

**Comment by effigies** [comment]
Has it been established that this Turtle snippet is valid with some other parser? By changing to a normal form `1.71e-12`:

```Turtle
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

<http://qudt.org/vocab/unit/MilliM-PER-YR>
  a <http://qudt.org/schema/qudt/Unit> ;
  <http://qudt.org/schema/qudt/conversionMultiplier> 1.71e-12 ;
  <http://qudt.org/schema/qudt/conversionOffset> 0e+00 ;
  <http://qudt.org/schema/qudt/description> "0.001-fold of the SI base unit metre divided by the unit year" ;
  <http://qudt.org/schema/qudt/hasQuantityKind> <http://qudt.org/vocab/quantitykind/Velocity> ;
  <http://qudt.org/schema/qudt/iec61360Code> "0112/2///62720#UAA868" ;
  <http://qudt.org/schema/qudt/uneceCommonCode> "H66" ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
  rdfs:isDefinedBy <http://qudt.org/vocab/unit> ;
  rdfs:label "MilliM PER YR" ;
  <http://www.w3.org/2004/02/skos/core#prefLabel> "millimetre per year" ;
```

I stll get an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cjmarkie/Projects/rdflib/rdflib/graph.py", line 1072, in parse
    parser.parse(source, self, **args)
  File "/home/cjmarkie/Projects/rdflib/rdflib/plugins/parsers/notation3.py", line 1888, in parse
    p.loadStream(source.getByteStream())
  File "/home/cjmarkie/Projects/rdflib/rdflib/plugins/parsers/notation3.py", line 444, in loadStream
    return self.loadBuf(stream.read())    # Not ideal
  File "/home/cjmarkie/Projects/rdflib/rdflib/plugins/parsers/notation3.py", line 450, in loadBuf
    self.feed(buf)
  File "/home/cjmarkie/Projects/rdflib/rdflib/plugins/parsers/notation3.py", line 476, in feed
    i = self.directiveOrStatement(s, j)
  File "/home/cjmarkie/Projects/rdflib/rdflib/plugins/parsers/notation3.py", line 497, in directiveOrStatement
    j = self.statement(argstr, i)
  File "/home/cjmarkie/Projects/rdflib/rdflib/plugins/parsers/notation3.py", line 735, in statement
    j = self.property_list(argstr, i, r[0])
  File "/home/cjmarkie/Projects/rdflib/rdflib/plugins/parsers/notation3.py", line 1074, in property_list
    "EOF found when expected verb in property list")
  File "/home/cjmarkie/Projects/rdflib/rdflib/plugins/parsers/notation3.py", line 1625, in BadSyntax
    raise BadSyntax(self._thisDoc, self.lines, argstr, i, msg)
rdflib.plugins.parsers.notation3.BadSyntax: at line 15 of <>:
Bad syntax (EOF found when expected verb in property list) at ^ in:
"...b'.w3.org/2004/02/skos/core#prefLabel> "millimetre per year" ;'^b'\n'"
```

The snippet also fails on a [validator](http://ttl.summerofcode.be/) I found on the first page of search.

**Comment by white-gecko** [comment]
Actually the syntax has to be:

```
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<http://qudt.org/vocab/unit/MilliM-PER-YR>
  a <http://qudt.org/schema/qudt/Unit> ;
  <http://qudt.org/schema/qudt/conversionMultiplier> 1.71e-12 ;
  <http://qudt.org/schema/qudt/conversionOffset> 0e+00 ;
  <http://qudt.org/schema/qudt/description> "0.001-fold of the SI base unit metre divided by the unit year" ;
  <http://qudt.org/schema/qudt/hasQuantityKind> <http://qudt.org/vocab/quantitykind/Velocity> ;
  <http://qudt.org/schema/qudt/iec61360Code> "0112/2///62720#UAA868" ;
  <http://qudt.org/schema/qudt/uneceCommonCode> "H66" ;
  rdfs:isDefinedBy <http://qudt.org/2.1/vocab/unit> ;
  rdfs:isDefinedBy <http://qudt.org/vocab/unit> ;
  rdfs:label "MilliM PER YR" ;
  <http://www.w3.org/2004/02/skos/core#prefLabel> "millimetre per year" .
```
